# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\python_xls\mytest.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(871, 590)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(120, 20, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(420, 390, 81, 41))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(340, 250, 160, 83))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(490, 30, 308, 211))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_20 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout_2.addWidget(self.pushButton_20, 3, 1, 1, 1)
        self.pushButton_26 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_26.setObjectName("pushButton_26")
        self.gridLayout_2.addWidget(self.pushButton_26, 0, 3, 1, 1)
        self.pushButton_28 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_28.setMaximumSize(QtCore.QSize(75, 23))
        self.pushButton_28.setObjectName("pushButton_28")
        self.gridLayout_2.addWidget(self.pushButton_28, 4, 2, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_2.addWidget(self.pushButton_16, 2, 0, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_2.addWidget(self.pushButton_17, 2, 1, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_2.addWidget(self.pushButton_14, 1, 1, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_2.addWidget(self.pushButton_15, 1, 2, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout_2.addWidget(self.pushButton_21, 3, 2, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout_2.addWidget(self.pushButton_23, 0, 0, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout_2.addWidget(self.pushButton_24, 0, 1, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_2.addWidget(self.pushButton_18, 2, 2, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout_2.addWidget(self.pushButton_19, 3, 0, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_22.setMinimumSize(QtCore.QSize(75, 0))
        self.pushButton_22.setMaximumSize(QtCore.QSize(75, 16777215))
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout_2.addWidget(self.pushButton_22, 4, 0, 1, 2)
        self.pushButton_25 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_25.setObjectName("pushButton_25")
        self.gridLayout_2.addWidget(self.pushButton_25, 0, 2, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_2.addWidget(self.pushButton_12, 1, 0, 1, 1)
        self.pushButton_29 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_29.setMaximumSize(QtCore.QSize(50, 23))
        self.pushButton_29.setObjectName("pushButton_29")
        self.gridLayout_2.addWidget(self.pushButton_29, 3, 3, 2, 1)
        self.pushButton_27 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_27.setObjectName("pushButton_27")
        self.gridLayout_2.addWidget(self.pushButton_27, 1, 3, 2, 1)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(60, 251, 131, 121))
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_3.addWidget(self.pushButton_5, 0, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_3.addWidget(self.pushButton_6, 0, 1, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.widget)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_3.addWidget(self.pushButton_10, 1, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_3.addWidget(self.pushButton_8, 1, 1, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.widget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_3.addWidget(self.pushButton_9, 1, 2, 1, 1)
        self.pushButton_30 = QtWidgets.QPushButton(self.widget)
        self.pushButton_30.setObjectName("pushButton_30")
        self.gridLayout_3.addWidget(self.pushButton_30, 2, 0, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.widget)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_3.addWidget(self.pushButton_13, 2, 1, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.widget)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_3.addWidget(self.pushButton_11, 2, 2, 1, 1)
        self.pushButton_31 = QtWidgets.QPushButton(self.widget)
        self.pushButton_31.setObjectName("pushButton_31")
        self.gridLayout_3.addWidget(self.pushButton_31, 3, 0, 1, 2)
        self.pushButton_32 = QtWidgets.QPushButton(self.widget)
        self.pushButton_32.setObjectName("pushButton_32")
        self.gridLayout_3.addWidget(self.pushButton_32, 3, 2, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_3.addWidget(self.pushButton_7, 0, 2, 1, 1)

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.close)
        self.pushButton_2.clicked.connect(Form.showMaximized)
        self.pushButton_3.clicked.connect(Form.showMinimized)
        self.pushButton_4.clicked.connect(Form.showFullScreen)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "这是一个示例"))
        self.pushButton.setText(_translate("Form", "Close"))
        self.pushButton_2.setText(_translate("Form", "最大化"))
        self.pushButton_3.setText(_translate("Form", "最小化"))
        self.pushButton_4.setText(_translate("Form", "全屏"))
        self.pushButton_20.setText(_translate("Form", "2"))
        self.pushButton_26.setText(_translate("Form", "-"))
        self.pushButton_28.setText(_translate("Form", "."))
        self.pushButton_16.setText(_translate("Form", "4"))
        self.pushButton_17.setText(_translate("Form", "5"))
        self.pushButton_14.setText(_translate("Form", "8"))
        self.pushButton_15.setText(_translate("Form", "9"))
        self.pushButton_21.setText(_translate("Form", "3"))
        self.pushButton_23.setText(_translate("Form", "Num"))
        self.pushButton_24.setText(_translate("Form", "/"))
        self.pushButton_18.setText(_translate("Form", "6"))
        self.pushButton_19.setText(_translate("Form", "1"))
        self.pushButton_22.setText(_translate("Form", "0"))
        self.pushButton_25.setText(_translate("Form", "*"))
        self.pushButton_12.setText(_translate("Form", "7"))
        self.pushButton_29.setText(_translate("Form", "enter"))
        self.pushButton_27.setText(_translate("Form", "+"))
        self.pushButton_5.setText(_translate("Form", "7"))
        self.pushButton_6.setText(_translate("Form", "8"))
        self.pushButton_10.setText(_translate("Form", "4"))
        self.pushButton_8.setText(_translate("Form", "5"))
        self.pushButton_9.setText(_translate("Form", "6"))
        self.pushButton_30.setText(_translate("Form", "1"))
        self.pushButton_13.setText(_translate("Form", "2"))
        self.pushButton_11.setText(_translate("Form", "3"))
        self.pushButton_31.setText(_translate("Form", "0"))
        self.pushButton_32.setText(_translate("Form", "."))
        self.pushButton_7.setText(_translate("Form", "9"))
